//state de productos
export const OBTERNER_PRODUCTOS_EXITO = "OBTERNER_PRODUCTOS_EXITO";

// state para pedido
export const SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO";
export const SELECCIONAR_LOCAL = "SELECCIONAR_LOCAL";
export const SELECCIONAR_CIUDAD = "SELECCIONAR_CIUDAD";
export const SELE = "SELECCIONAR_CIUDAD";

export const CONFIRMAR_ORDENAR_PLATILLO = "CONFIRMAR_ORDENAR_PLATILLO";
export const MOSTRAR_RESUMEN = "MOSTRAR_RESUMEN";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const PEDIDO_ORDENADO = "PEDIDO_ORDENADO";
export const REINICIAR_PEDIDO = "REINICIAR_PEDIDO";

export const VISIBLE_MODAL = "VISIBLE_MODAL";

//state de restaurantes
export const OBTENER_RESTAURANTES = "OBTENER_RESTAURANTES";
export const OBTENER_ORDENES = "OBTENER_ORDENES";
export const OBTENER_FACTURA = "OBTENER_FACTURA";
export const OBTENER_IMAGENES = "OBTENER_IMAGENES";
export const OBTENER_TOCKEN = "OBTENER_TOCKEN";
